# The following code is generated by Gemini for test of API purpose.

import pyaudio
import numpy as np

# 音声出力の設定
CHUNK = 1024  # 一度に処理するサンプル数
FORMAT = pyaudio.paFloat32  # 音声データのフォーマット
CHANNELS = 2  # チャンネル数 (ステレオ)
RATE = 44100  # サンプリングレート
DEVICE_INDEX = 1

# PyAudioオブジェクトの作成
p = pyaudio.PyAudio()

# debug
print(p.get_device_count())
print(p.get_device_info_by_index(1))
# end of debug

# ストリームのオープン
stream = p.open(format=FORMAT,
                channels=CHANNELS,
                rate=RATE,
                output=True,
                output_device_index=DEVICE_INDEX,
                frames_per_buffer=CHUNK)

# 任意の波形データを生成 (ここではサイン波)
t = np.linspace(0, 2, RATE*2)  # 2秒分の時間軸
freq = 40  # 周波数
data = (np.sin(2*np.pi*freq*t) + np.sin(10.0 * t)).astype(np.float32)

# 音声出力
stream.write(data.tobytes())

# ストリームのクローズ
stream.stop_stream()
stream.close()

# PyAudioオブジェクトの終了
p.terminate()